name: CI Tests

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12-dev"]
    runs-on: ${{ matrix.os }}
    name: Tests on Python ${{ matrix.python-version }} (${{ matrix.os }})

    services:
      rabbitmq:
        image: rabbitmq:management
        options: --health-cmd="curl --silent --fail http://localhost:15672/healthcheck || exit 1" --health-timeout=30s --health-retries=3 --health-start-period=10s --health-interval=5s
        ports:
          - 5672:5672  # RabbitMQ port
          - 15672:15672  # RabbitMQ management UI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install Pyro4==4.81

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install libffi

      - name: Start Pyro4 Name Server
        run: |
          pkill -f pyro4-ns || true
          pyro4-ns &
          sleep 15

      - name: Wait for RabbitMQ to be ready
        run: |
          while ! curl --silent --fail http://localhost:15672; do
            echo "Waiting for RabbitMQ to be ready..."
            sleep 2
          done

      - name: Run tests with coverage
        run: |
          pytest tests/
